version: "3.9"
services:
  db:
    image: docker.arvancloud.ir/postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: {}
